server:
    port: 8082

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/hotel_spring?autoReconnect=true
        username: root
        password: qwertDBqwert
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa.show-sql: true
    flyway:
#        locations: classpath:db/migration
#        baselineOnMigrate: true
